export const listData = {
  subscribes: [
    {
      imgUrl: "./img/profile/profile-img-1.jpeg",
      alt: "User",
      mainText: "N E W",
      secondaryText: "Развитие",
      badgeNumber: null,
    },
    {
      imgUrl: "./img/profile/profile-img-2.jpeg",
      alt: "User",
      mainText: "Aesthetics",
      secondaryText: "Стиль",
      badgeNumber: 1,
    },
    {
      imgUrl: "./img/profile/profile-img-3.jpeg",
      alt: "User",
      mainText: "дом твоей эстетики",
      secondaryText: "Творчество",
      badgeNumber: 4,
    },
    {
      imgUrl: "./img/profile/profile-img-4.jpeg",
      alt: "User",
      mainText: "wailet",
      secondaryText: "Искусство",
      badgeNumber: null,
    },
    {
      imgUrl: "./img/profile/profile-img-5.jpeg",
      alt: "User",
      mainText: "A W E S O M E",
      secondaryText: "Стиль",
      badgeNumber: 6,
    },
    {
      imgUrl: "./img/profile/profile-img-6.jpeg",
      alt: "User",
      mainText: "minimalism",
      secondaryText: "Фотография",
      badgeNumber: null,
    },
    {
      imgUrl: "./img/profile/profile-img-7.jpeg",
      alt: "User",
      mainText: "Словарный запас",
      secondaryText: "Литература",
      badgeNumber: null,
    },
    {
      imgUrl: "./img/profile/profile-img-8.jpeg",
      alt: "User",
      mainText: "Look",
      secondaryText: "Мода",
      badgeNumber: 8,
    },
  ],
  closeFriends: [
    {
      imgUrl: "./img/users/aleksandr-maykov.jpeg",
      alt: "User",
      mainText: "Александр Майков",
      secondaryText: "Онлайн",
      badgeNumber: null,
      isOnline: true,
    },
    {
      imgUrl: "./img/users/aleksandr-maykov.jpeg",
      alt: "User",
      mainText: "Александр Майков",
      secondaryText: "Онлайн",
      badgeNumber: 5,
      isOnline: false,
    },
    {
      imgUrl: "./img/users/aleksandr-maykov.jpeg",
      alt: "User",
      mainText: "Александр Майков",
      secondaryText: "Онлайн",
      badgeNumber: 9,
      isOnline: true,
    },
  ],
  music: [
    {
      imgUrl: "./img/music/album-1.png",
      alt: "Album",
      mainText: "Pieces",
      secondaryText: "Andrew Belle",
    },
    {
      imgUrl: "./img/music/album-2.png",
      alt: "Album",
      mainText: "In the Wind",
      secondaryText: "On-The-Go",
    },
    {
      imgUrl: "./img/music/album-3.png",
      alt: "Album",
      mainText: "On you own",
      secondaryText: "Meltt",
    },
    {
      imgUrl: "./img/music/album-4.png",
      alt: "Album",
      mainText: "Infinity",
      secondaryText: "James Young",
    },
    {
      imgUrl: "./img/music/album-5.png",
      alt: "Album",
      mainText: "Let me follow",
      secondaryText: "Son Lux",
    },
    {
      imgUrl: "./img/music/album-6.png",
      alt: "Album",
      mainText: "Youth",
      secondaryText: "Glass Animals",
    },
  ],
};
